name: alaneicker.com

run-name: ${{ github.actor }} is Running Build and Deployment Pipeline

runs-on: ubuntu-latest

on:
  push:
    branches: ['master']

jobs:
  Test:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.x
          cache: npm
      - name: Install
        run: npm install --legacy-peer-deps
      - name: Test
        run: npm run test
